version: '{build}'
skip_tags: true
image: Visual Studio 2019

build_script:
  - ps: ./Build.ps1

test: off

artifacts:
  - path: artifacts/Seq.App.*.nupkg
  
deploy:
  - provider: NuGet
    api_key:
      secure: qK2UsTAZYO03iM4OyxSjQjaoMrx2vQm9yswB2iQ93X5Cr9+hyyCh182f9WSSjecF
    skip_symbols: true
    on:
      branch: /^(master|dev)$/
