name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Invoke Build.ps1 with PowerShell Core
        shell: pwsh
        run: ./Build.ps1
        