name: Publish

on:
  workflow_run:
    workflows: ["Build"]
    branches: [master, dev]
    types: [completed]

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Push
        shell: pwsh
        run: |
          dotnet nuget push (get-item ./artifacts/*.nupkg).FullName --api-key="$env:NUGET_API_KEY"
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
